package dgmp.sigrh.auth.model.events.types.auth;


import dgmp.sigrh.auth.model.events.types.EventType;

public enum AssignationEventTypes implements EventType
{
    ASSIGNATION_UPDATED("ASSIGNATION_UPDATED"),
    ROLE_ASSIGNED_TO_USER("ROLE_ASSIGNED_TO_USER"),
    PRIVILEGE_ASSIGNED_TO_USER("PRIVILEGE_ASSIGNED_TO_USER"),
    ROLE_REVOKED_TO_USER("ROLE_REVOKED_TO_USER"),
    PRIVILEGE_REVOKED_TO_USER("PRIVILEGE_REVOKED_TO_USER"),

    PRIVILEGE_ASSIGNED_TO_ROLE("PRIVILEGE_ASSIGNED_TO_ROLE"),
    PRIVILEGE_REVOKED_TO_ROLE("PRIVILEGE_REVOKED_TO_ROLE"),

    ASSIGNATION_ACTIVATED("ASSIGNATION_ACTIVATED"),
    ASSIGNATION_DEACTIVATED("ASSIGNATION_DEACTIVATED"),
    ASSIGNATION_SET_AS_DEFAULT("ASSIGNATION_SET_AS_DEFAULT"),
    ASSIGNATION_SET_AS_NONE_DEFAULT("ASSIGNATION_SET_AS_NONE_DEFAULT"),
    VALIDITY_PERIOD_CHANGED("VALIDITY_PERIOD_CHANGED");

    String name;
    AssignationEventTypes(String name)
    {
        this.name = name;
    }
    AssignationEventTypes() { }

    @Override
    public String toString() {
        return name;
    }
}
